//
// Created by tim on 17.11.18.
//

#ifndef FTMODULE_SENSORENUMDEFINITION_H
#define FTMODULE_SENSORENUMDEFINITION_H

enum PROCESS_TYPE {
  IMU = 0,
  NUM_PROCESS_SENSORS
};

enum UPDATE_TYPE {
  TAG = 0,
  POSEMEAS,
  FEATUREOBS,
  NUM_UPDATE_SENSORS
};

#endif //FTMODULE_SENSORENUMDEFINITION_H
